### ISSUE TITLE
Use localized Downloads folder

### ISSUE THREAD

**Issue by Victorq10** [ronniedroid/getnf#10]
Use command to get localized directory name
`xdg-user-dir DOWNLOAD`

Replace
`downDir="$HOME/Downloads/NerdFonts"`
with
`downDir="$(xdg-user-dir DOWNLOAD)/NerdFonts"`
or
`downDir="$(command -V xdg-user-dir &> /dev/null && xdg-user-dir DOWNLOAD || echo "$HOME/Downloads")/NerdFonts"`

the last command will check if `xdg-user-dir` command exists

**Comment by ronniedroid** [comment]
That is a good idea, updated. Thanks.
