### ISSUE TITLE
line 51: fzf: command not found

### ISSUE THREAD

**Issue by jacobsayono** [ronniedroid/getnf#11]
running `getnf` in terminal
returns this error, otherwise everything was ok.
i'm using lunarvim but the icons are still not showing up!

edit: `fc-cache -f -v` in terminal helps but the front page of lunarvim when running `lvim` doesn't show proper icons

![Screenshot from 2022-11-24 01-10-25](https://user-images.githubusercontent.com/46827431/203743299-26bcd30f-393d-46fc-8995-2598d2442cdb.png)

**Comment by ronniedroid** [comment]
you will need to install `fzf` before you run getnf, it is a dependency.

**Comment by jacobsayono** [comment]
just had to install a nerd font and select it (in terminal preferences) and icons are now showing up!

**Comment by ronniedroid** [comment]
I think you were in the right place for the wrong reason. anyways, take care.
