### ISSUE TITLE
Download newer font version if available

### ISSUE THREAD

**Issue by meinzer1899** [ronniedroid/getnf#12]
first things first: thanks for the script, really appreciated

Currently, if you select a font, `getnf` checks if the font is already available (i.e. in the fc-list). If yes, the script exits.

Lately, I saw that there is a new font version of the font I use at the [Nerd Font repository](https://github.com/ryanoasis/nerd-fonts/releases) , section _Updates_.

Are you interested in adding a version check that checks if the font version on the Nerd Font remote is more recent, and updates the local font accordingly? I would provide an approach.

**Comment by ronniedroid** [comment]
Hey, you are welcome,

Yes, I think that would be amazing, would you like to submit a PR, or an issue explaining your approach?
