### ISSUE TITLE
rockylinux

### ISSUE THREAD

**Issue by huangyt** [ronniedroid/getnf#14]
run install.sh, no result.
what is fzf ?
there's no result by command "dnf search fzf " in rockylinux terminal.
thx!

**Comment by SalmaAlassal** [comment]
**fzf** is a command-line fuzzy finder tool that can be used to search for files, directories.

Regarding your issue, it seems that the fzf package is not available in the default repositories for Rocky Linux. You can try to install it from a third-party repository or by manually building and installing it from the source code.

**Comment by ronniedroid** [comment]
you can find installation instructions here: https://github.com/junegunn/fzf#installation
