### ISSUE TITLE
Error with missing dependency

### ISSUE THREAD

**Issue by laaledesiempre** [ronniedroid/getnf#19]
First of all, i use arch btw.
When you use the cli tool and you dont have unzip installed, it throws the error and the font doesnt install, 
but in the cli menu font doesnt appear anymore(because is "already installed" even when is not), so you cant installed it later

> ## How i to get that error

install any font in any distro that doesnt have unzip installed.

---

## Possibly solution:
 Checking if you can unzip before creating all directories and everything

---

Awesome app by the way, best app to install nerdfonts, i cant say thanks enough

**Comment by ronniedroid** [comment]
fix by cd65947

in case you get in the same situation again, for any reason, use the `-F` flag to force install fonts.

You are welcome :-)
