### ISSUE TITLE
list is emply

### ISSUE THREAD

**Issue by HernandoR** [ronniedroid/getnf#31]
Hi,

any suggestions?

![image](https://github.com/ronniedroid/getnf/assets/45709656/fb1fe431-605e-445e-971d-9ccc114f80dd)

**Comment by ronniedroid** [comment]
try with `-f`, but maybe you reached your github api limit.

**Comment by HernandoR** [comment]
I'm afraid there must be something wrong around line 69. I managed to use Cloudflare to proxy the request. therefore `curl -s "$nerdfontsrepo/contents/patched-fonts?ref=master"` gives what should be. but `curl -s "$nerdfontsrepo/contents/patched-fonts?ref=master"awk -F'"''/tag_name/{print $4}` gives nothing as shown in img.

`getnf` however can give me one font to install :`0xProto` which is the fist in the list

<img width="935" alt="image" src="https://github.com/ronniedroid/getnf/assets/45709656/4e207893-1d9a-4571-b66b-48efa77cab12">

**Comment by HernandoR** [comment]
found solution, that works for me, please review #32
