### ISSUE TITLE
Too many `/`

### ISSUE THREAD

**Issue by trimclain** [ronniedroid/getnf#36]
Is there any reason you reverted my changes with this [commit](https://github.com/ronniedroid/getnf/commit/663afdeda8695683b89540365edc4da04640e325)?
The reason for my initial change was that if a user has `xdg-user-dir` installed, it will return the path with a `/` at the end. So for me the output of `xdg-user-dir DOWNLOAD` is `/home/trimclain/downloads/`. This way the `down_dir` variable is `/home/trimclain/downloads//NerdFonts`. As you can see there are 2 slashes as last separator. Although this still does work in other places, the [info message](https://github.com/ronniedroid/getnf/blob/master/getnf#L124) about the removing download looks wrong:

![image](https://github.com/ronniedroid/getnf/assets/84108846/bcc3344a-254e-45a1-94c3-9526c120fe9f)

Can you give me an example where it didn't work for you?

**Comment by ronniedroid** [comment]
Oh, I was not thinking much when I did the change.

Was trying to fix a bug where I got `~/DownloadsNerdFonts` instead of `~/Downloads/Nerdfonts`

I will look at it tomorrow if I got time.

**Comment by ronniedroid** [comment]
```sh
ronnie@machine ~> xdg-user-dir DOWNLOAD
/home/ronnie/Downloads
```

**Comment by trimclain** [comment]
Thanks, I found the problem in my config
