### ISSUE TITLE
Add more fonts to the list

### ISSUE THREAD

**Issue by Yushi5058** [ronniedroid/getnf#39]
Hello, 
I suggest adding more fonts to the list, and along with the pull request  [here](https://github.com/ronniedroid/getnf/pull/38) be able to install whatever font we would like. I like to add the maple-font.

Thanks !

**Comment by trimclain** [comment]
The main point of this project is to download and install [Nerd Fonts](https://www.nerdfonts.com/#home) from the terminal using the official [source](https://www.nerdfonts.com/font-downloads). If you want to suggest adding a different source for Nerd Fonts, you need to provide a link to it.

**Comment by Yushi5058** [comment]
I see, maple font is not a nerd font. Thanks for the answer
